apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: mattermost
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
spec:
  namespaceSelector:
    matchNames:
      - mattermost-cluster
  selector:
    matchLabels:
      app: mattermost
  endpoints:
    - port: metrics
      path: /metrics
      interval: 30s