apiVersion: v1
kind: Secret
metadata: 
  name: mattermost-secret
  namespace: default
type: Opaque
stringData: 
  MM_SQLSETTINGS_DATASOURCE: "postgres://mmuser:mmpassword@postgres:5432/mattermost?sslmode=disable"