apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret 
  namespace: mattermost-cluster
type: Opaque
stringData: 
  POSTGRES_DB: mattermost
  POSTGRES_USER: mmuser
  POSTGRES_PASSWORD: mmpassword